geb's GlazeWM config as of Jan 14, 2024

The GlazeWM project can be found here:
https://github.com/glzr-io/glazewm


general:
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to jump the cursor between windows focused by the WM.
  cursor_follow_focus: false

  # Whether to switch back and forth between the previously focused workspace
  # when focusing the current workspace.
  toggle_workspace_on_refocus: true

  # Whether to show floating windows as always on top.
  show_floating_on_top: true

  # Amount to move floating windows by (eg. when using `alt+<hjkl>` on a floating window)
  floating_window_move_amount: "5%"

  # *Strongly* recommended to set to 'false'. Whether to globally enable/disable
  # window transition animations (on minimize, close, etc). Set to 'unchanged'
  # to make no setting changes.
  window_animations: "unchanged"

gaps:
  # Gap between adjacent windows.
  inner_gap: "20px"

  # Gap between windows and the screen edge.
  outer_gap: "20px"

# Highlight active/inactive windows with a colored border.
# ** Exclusive to Windows 11 due to API limitations.
focus_borders:
  active:
    enabled: false
    color: "#0000ff"

  inactive:
    enabled: false
    color: "#ff0000"




# My scheme
# -------------------------

# Foreground
define: &fg '#fddfdd'

# Background
define: &bg 'transparent'

# windows dark mode color: "#202020"
# semi-transparent: "#0000007f"

# -------------------------


bar:
  height: "20px"
  position: "top"
  BACKGROUND_opacity: 0
  foreground: *fg
  background: *bg
  font_family: "HeavyData Nerd Font"
  #font_family: "3270 Nerd Font"
  #font_family: "ProggyClean Nerd Font"
  #font_family: "GohuFont 14 Nerd Font Mono"
  #font_family: "MartianMono Nerd Font Mono"
  font_size: "17px"
  offset_x: "20"
  offset_y: "20"
  border_radius: "0"
  components_left:
#    - type: "image"
#      source: "C:\\Users\\geb\\.glaze-wm\\logo.png"
#      padding: "0 8px 0 0"
#      margin: "0"
#    - type: "text"
#      text: "⊞"
    - type: "workspaces"
      # use 'focused_workspace_' to define properties for that chunk
      #focused_workspace_background: "#001930"
      focused_workspace_background: *fg
      focused_workspace_foreground: "#transparent"
      focused_workspace_border_width: "0"
      focused_workspace_border_radius: "8px"
      focused_workspace_border_color: "blue"
      padding: "0 0"
      padding: ""
    - type: "tiling direction"
      label_horizontal: "h"
      label_vertical: "v"
      margin: "0 1px"
      padding: "0 7px"
      border_width: 1px
      border_radius: 0px
      border_color: *fg
    - type: "binding mode"
      background: *fg
      foreground: "transparent"
      margin: "0 8px"

  components_center:
    - type: "window title"
      left_click_command: "exec C:/Users/geb/.glaze-wm/tv.ahk"

  components_right:
    - type: "system tray"
      label_expand_text: "iii"
      label_collapse_text: "iii "
      padding: "3px 8px"

    - type: "cpu"
      label: "CPU: {percent_usage}"
      # How often this counter is refreshed.
      refresh_interval_ms: 3000
      padding: "0 8px"

      # adding blank text box to trigger click event
    - type: "text"
      foreground: "transparent"
      background: "transparent"
      text: "MMMM" # Adjust number of spaces based on size of component
      margin: 0 0 0 -70px # Moves it left on top of the previous component
      padding: 0px
      left_click_command: "exec taskmgr"

    - type: "memory"
      label: "RAM: {percent_usage}"
      # How often this counter is refreshed.
      refresh_interval_ms: 3000
      padding: "0 8px"
      left_click_command: "exec taskmgr"

      # adding blank text box to trigger click event
    - type: "text"
      foreground: "transparent"
      background: "transparent"
      text: "MMMM" # Adjust number of spaces based on size of component
      margin: 0 0 0 -70px # Moves it left on top of the previous component
      padding: 0px
      left_click_command: "exec taskmgr"

    - type: "network"
      label_no_internet: "offline"
      label_ethernet: "eth"
      label_wifi_strength_0: "online"
      label_wifi_strength_25: "online"
      label_wifi_strength_50: "online"
      label_wifi_strength_75: "online"
      label_wifi_strength_100: "online"
      padding: "0 8px"

      # adding black text box to trigger click event
    - type: "text"
      foreground: "transparent"
      background: "transparent"
      text: "MM" # Adjust number of spaces based on size of component
      margin: 0 0 0 -20px # Moves it left on top of the previous component
      padding: 0px
      left_click_command: "exec ms-settings:network"

    - type: "clock"
      # Documentation on formatting date/time string:
      # https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
      time_formatting: "hh:mm"
      padding: "0 8px"
    - type: "clock"
      # Documentation on formatting date/time string:
      # https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
      time_formatting: "ddd d"
      padding: "0 8px"





# workspaces

workspaces:
  - name: "1"
    display_name: "a"
    keep_alive: true
  - name: "2"
    display_name: "b"
    keep_alive: true
  - name: "3"
    display_name: "c"
    keep_alive: true
  - name: "4"
    display_name: "d"
    keep_alive: true
  - name: "5"
    display_name: "e"
    keep_alive: true
  - name: "6"
    display_name: "f"
    keep_alive: true
  - name: "7"
    display_name: "g"
    keep_alive: true
  - name: "8"
    display_name: "h"
    keep_alive: true
  - name: "9"
    display_name: "i"
    keep_alive: true


# window rules

window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.

  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost/"

  - command: "set floating"
    match_class_name: "#32770"

  - command: 'set floating'
    match_title: 'Picture in picture'

  - command: 'ignore'
    match_title: 'Picture-in-Picture'

  - command: 'ignore'
    match_title: 'Picture-in-Picture'

  - command: "ignore"
    match_title: "Run"

  - command: "ignore"
    match_title: "Miniplayer"

  - command: "ignore"
    match_process_name: "RoundedTB"

  - command: 'set floating'
    match_process_name: "NextDNS"

  - command: 'set floating'
    match_process_name: "LocalSend"

  - command: 'set floating'
    match_process_name: "StoreDesktopExtension"

  - command: "ignore"
    match_process_name: "cs2"

  - command: "ignore"
    match_process_name: "VALORANT"

  - command: "ignore"
    match_process_name: "snipaste"

  - command: "set floating"
    match_process_name: "AppleTV"

  - command: "ignore"
    match_process_name: "AMPLibraryAgent"

  - command: "set floating" 
    match_title: "Jellyfin Media Player"

  - command: "ignore"
    match_title: Calculator

# the rest of these came from a list of common exclusions found on github:
  - command: "set floating"
    match_process_name: CredentialUIBroker
  - command: "set floating"
    match_class_name: Chrome_RenderWidgetHostHWND
  - command: "set floating"
    match_class_name: TApplication
  - command: "set floating"
    match_class_name: TWizardForm
  - command: "set floating"
    match_class_name: SunAwtDialog
  - command: "set floating"
    match_class_name: _WwB
  - command: "set floating"
    match_class_name: _WwB
  - command: "set floating"
    match_class_name: _WwB
  - command: "set floating"
    match_title: Microsoft Teams Notifications
  - command: "set floating"
    match_class_name: _WwB
  - command: "set floating"
    match_class_name: MozillaTaskbarPreviewClass
  - command: "set floating"
    match_process_name: NohBoard
  - command: "set floating"
    match_process_name: Paradox Launcher
  - command: "set floating"
    match_process_name: PowerToys.ColorPickerUI
  - command: "set floating"
    match_process_name: PowerToys.ImageResizer
  - command: "set floating"
    match_process_name: ProcessHacker
  - command: "set floating"
    match_class_name: SunAwtDialog
  - command: "set floating"
    match_process_name: QuickLook
  - command: "set floating"
    match_process_name: RepoZ
  - command: "set floating"
    match_class_name: Chrome_RenderWidgetHostHWND
  - command: "set floating"
    match_class_name: Chrome_RenderWidgetHostHWND
  - command: "set floating"
    match_class_name: Shell_Dialog
  - command: "set floating"
    match_class_name: TaskManagerWindow
  - command: "set floating"
    match_process_name: tcconfig
  - command: "set floating"
    match_process_name: TranslucentTB
  - command: "set floating"
    match_class_name: OperationStatusWindow
  - command: "set floating"
    match_title: Control Panel
  - command: "set floating"
    match_class_name: MsiDialogCloseClass
  - command: "set floating"
    match_title: Hotkey sink
  - command: "set floating"
    match_process_name: Zoom
  - command: "set floating"
    match_process_name: ueli
  - command: "set floating"
    match_process_name: System

  # Some applications have borders that extend past the normal border size for some reason:
  - command: "resize borders 0px 0px 0px 0px"
    match_process_name: "steam"

  - command: "resize borders 0px 0px 0px 0px"
    match_process_name: "Discord"





# keybinds

binding_modes:
  - name: "resize"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - command: "resize width -2%"
        bindings: ["A", "Left"]
      - command: "resize width +2%"
        bindings: ["D", "Right"]
      - command: "resize height +2%"
        bindings: ["W", "Up"]
      - command: "resize height -2%"
        bindings: ["S", "Down"]
      # Press enter/escape to return to default keybindings.
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["Alt+A"]
  - command: "focus right"
    bindings: ["Alt+D"]
  - command: "focus up"
    bindings: ["Alt+W"]
  - command: "focus down"
    bindings: ["Alt+S"]

  # Move focused window in a given direction.
  - command: "move left"
    bindings: ["Alt+Shift+A", "Alt+Shift+Left"]
  - command: "move right"
    bindings: ["Alt+Shift+D", "Alt+Shift+Right"]
  - command: "move up"
    bindings: ["Alt+Shift+W", "Alt+Shift+Up"]
  - command: "move down"
    bindings: ["Alt+Shift+S", "Alt+Shift+Down"]

  # Resize focused window by a percentage or pixel amount.
  - command: "resize width -2%"
    binding: "Control+Alt+A"
  - command: "resize width +2%"
    binding: "Control+Alt+D"
  - command: "resize height +2%"
    binding: "Control+Alt+W"
  - command: "resize height -2%"
    binding: "Control+Alt+S"

  # As an alternative to the resize keybindings above, resize mode enables resizing via
  # HJKL or arrow keys. The binding mode is defined above with the name "resize".
  - command: "binding mode resize"
    binding: "Alt+R"

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - command: "tiling direction toggle"
    binding: "Alt+V"

  # Change focus between floating / tiling windows.
  - command: "focus mode toggle"
    binding: "Alt+X"

  # Change the focused window to be floating / tiling.
  - command: "toggle floating"
    binding: "Alt+Shift+X"

  # Change the focused window to be maximized / unmaximized.
  - command: "toggle maximized"
    binding: "Alt+F"

  # Minimize focused window.
  - command: "set minimized"
    binding: "Alt+E"

  # Close focused window.
  - command: "close"
    binding: "Alt+Q"

  # Kill GlazeWM process safely.
  - command: "exit wm"
    binding: "Alt+Shift+Q"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "Alt+Shift+R"

  # Launch CMD terminal (alternatively `exec cmd` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  #- command: "exec wt"
  #  binding: "Alt+Enter"
  - command: "exec C:/Users/geb/AppData/Local\Programs/anytype/Anytype.exe"
    binding: "Alt+Enter"

  - command: "exec Explorer.exe"
    binding: "Alt+Shift+F"

  # Focus the workspace that last had focus.
  - command: "focus workspace recent"
    binding: "Control+Shift+Tab"

  # Focus the next/previous workspace defined in `workspaces` config.
  - command: "focus workspace next"
    binding: "Alt+C"
  - command: "focus workspace prev"
    binding: "Alt+Z"

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace 7"
    binding: "Alt+7"
  - command: "focus workspace 8"
    binding: "Alt+8"
  - command: "focus workspace 9"
    binding: "Alt+9"


  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "Alt+Shift+6"
  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "Alt+Shift+7"
  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "Alt+Shift+8"
  - commands: ["move to workspace 9", "focus workspace 9"]
    binding: "Alt+Shift+9"